@startuml
skinparam shadowing false
skinparam responseMessageBelowArrow false
skinparam DefaultFontColor #222
skinparam TitleFontSize 25
skinparam NoteBorderColor #teal
skinparam NoteBackgroundColor #powderblue
skinparam NoteFontColor #444
skinparam DatabaseBorderColor #teal
skinparam DatabaseBackgroundColor #bisque

skinparam sequence {
  ParticipantBorderThickness 1
  ParticipantBorderColor #teal
  ParticipantBackgroundColor #teal
  ParticipantFontColor #white
  ParticipantFontSize 14
  ParticipantFontStyle bold
  LifeLineBorderColor #teal
  LifeLineBackgroundColor #aliceblue
  ArrowColor #teal
  ActorBorderColor #teal
  GroupBorderThickness 1
  GroupBorderColor #teal
  GroupHeaderFontColor #white
  GroupBackgroundColor #teal
  GroupFontColor #teal
}

header Đăng ký
title Luồng đăng ký
autonumber

actor "User" as user
participant "Client" as client
participant "Backend" as be
database DB


user -> client++: Bấm vào nút đăng ký trên màn hình
client --> user: Hiển thị giao diện màn hình đăng ký
user -> client: Điền thông tin email,tên, mật khẩu và bấm nút đăng nhập
alt form hợp lệ
client ->be++: Gọi API đăng ký
be -> DB++: Lưu dữ liệu thông tin
DB --> be: Trả kết quả
DB--
alt Dữ liệu hợp lệ
be --> client: Trả về thông tin tài khoản,jwt token
client --> user: Hiển thị ra thông báo đăng ký thành công
else Dữ liệu không hợp lệ
be --> client: Trả về lỗi
client --> user: Hiển thị ra thông báo lỗi
end
else form không hợp lệ
client --> user: Hiển thị thông báo lỗi
end

@enduml